// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: linkedca/provisioners.proto

package linkedca

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Provisioner_Type int32

const (
	Provisioner_NOOP   Provisioner_Type = 0
	Provisioner_JWK    Provisioner_Type = 1
	Provisioner_OIDC   Provisioner_Type = 2
	Provisioner_GCP    Provisioner_Type = 3
	Provisioner_AWS    Provisioner_Type = 4
	Provisioner_AZURE  Provisioner_Type = 5
	Provisioner_ACME   Provisioner_Type = 6
	Provisioner_X5C    Provisioner_Type = 7
	Provisioner_K8SSA  Provisioner_Type = 8
	Provisioner_SSHPOP Provisioner_Type = 9
	Provisioner_SCEP   Provisioner_Type = 10
)

// Enum value maps for Provisioner_Type.
var (
	Provisioner_Type_name = map[int32]string{
		0:  "NOOP",
		1:  "JWK",
		2:  "OIDC",
		3:  "GCP",
		4:  "AWS",
		5:  "AZURE",
		6:  "ACME",
		7:  "X5C",
		8:  "K8SSA",
		9:  "SSHPOP",
		10: "SCEP",
	}
	Provisioner_Type_value = map[string]int32{
		"NOOP":   0,
		"JWK":    1,
		"OIDC":   2,
		"GCP":    3,
		"AWS":    4,
		"AZURE":  5,
		"ACME":   6,
		"X5C":    7,
		"K8SSA":  8,
		"SSHPOP": 9,
		"SCEP":   10,
	}
)

func (x Provisioner_Type) Enum() *Provisioner_Type {
	p := new(Provisioner_Type)
	*p = x
	return p
}

func (x Provisioner_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provisioner_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_linkedca_provisioners_proto_enumTypes[0].Descriptor()
}

func (Provisioner_Type) Type() protoreflect.EnumType {
	return &file_linkedca_provisioners_proto_enumTypes[0]
}

func (x Provisioner_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Provisioner_Type.Descriptor instead.
func (Provisioner_Type) EnumDescriptor() ([]byte, []int) {
	return file_linkedca_provisioners_proto_rawDescGZIP(), []int{0, 0}
}

type Provisioner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorityId      string              `protobuf:"bytes,2,opt,name=authority_id,json=authorityId,proto3" json:"authority_id,omitempty"`
	Type             Provisioner_Type    `protobuf:"varint,3,opt,name=type,proto3,enum=linkedca.Provisioner_Type" json:"type,omitempty"`
	Name             string              `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Details          *ProvisionerDetails `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	Claims           *Claims             `protobuf:"bytes,6,opt,name=claims,proto3" json:"claims,omitempty"`
	X509Template     []byte              `protobuf:"bytes,7,opt,name=x509_template,json=x509Template,proto3" json:"x509_template,omitempty"`
	X509TemplateData []byte              `protobuf:"bytes,8,opt,name=x509_template_data,json=x509TemplateData,proto3" json:"x509_template_data,omitempty"`
	SshTemplate      []byte              `protobuf:"bytes,9,opt,name=ssh_template,json=sshTemplate,proto3" json:"ssh_template,omitempty"`
	SshTemplateData  []byte              `protobuf:"bytes,10,opt,name=ssh_template_data,json=sshTemplateData,proto3" json:"ssh_template_data,omitempty"`
}

func (x *Provisioner) Reset() {
	*x = Provisioner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedca_provisioners_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Provisioner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provisioner) ProtoMessage() {}

func (x *Provisioner) ProtoReflect() protoreflect.Message {
	mi := &file_linkedca_provisioners_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provisioner.ProtoReflect.Descriptor instead.
func (*Provisioner) Descriptor() ([]byte, []int) {
	return file_linkedca_provisioners_proto_rawDescGZIP(), []int{0}
}

func (x *Provisioner) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Provisioner) GetAuthorityId() string {
	if x != nil {
		return x.AuthorityId
	}
	return ""
}

func (x *Provisioner) GetType() Provisioner_Type {
	if x != nil {
		return x.Type
	}
	return Provisioner_NOOP
}

func (x *Provisioner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Provisioner) GetDetails() *ProvisionerDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Provisioner) GetClaims() *Claims {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *Provisioner) GetX509Template() []byte {
	if x != nil {
		return x.X509Template
	}
	return nil
}

func (x *Provisioner) GetX509TemplateData() []byte {
	if x != nil {
		return x.X509TemplateData
	}
	return nil
}

func (x *Provisioner) GetSshTemplate() []byte {
	if x != nil {
		return x.SshTemplate
	}
	return nil
}

func (x *Provisioner) GetSshTemplateData() []byte {
	if x != nil {
		return x.SshTemplateData
	}
	return nil
}

type ProvisionerDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*ProvisionerDetails_JWK
	//	*ProvisionerDetails_OIDC
	//	*ProvisionerDetails_GCP
	//	*ProvisionerDetails_AWS
	//	*ProvisionerDetails_Azure
	//	*ProvisionerDetails_ACME
	//	*ProvisionerDetails_X5C
	//	*ProvisionerDetails_K8SSA
	//	*ProvisionerDetails_SSHPOP
	//	*ProvisionerDetails_SCEP
	Data isProvisionerDetails_Data `protobuf_oneof:"data"`
}

func (x *ProvisionerDetails) Reset() {
	*x = ProvisionerDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedca_provisioners_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvisionerDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionerDetails) ProtoMessage() {}

func (x *ProvisionerDetails) ProtoReflect() protoreflect.Message {
	mi := &file_linkedca_provisioners_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionerDetails.ProtoReflect.Descriptor instead.
func (*ProvisionerDetails) Descriptor() ([]byte, []int) {
	return file_linkedca_provisioners_proto_rawDescGZIP(), []int{1}
}

func (m *ProvisionerDetails) GetData() isProvisionerDetails_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *ProvisionerDetails) GetJWK() *JWKProvisioner {
	if x, ok := x.GetData().(*ProvisionerDetails_JWK); ok {
		return x.JWK
	}
	return nil
}

func (x *ProvisionerDetails) GetOIDC() *OIDCProvisioner {
	if x, ok := x.GetData().(*ProvisionerDetails_OIDC); ok {
		return x.OIDC
	}
	return nil
}

func (x *ProvisionerDetails) GetGCP() *GCPProvisioner {
	if x, ok := x.GetData().(*ProvisionerDetails_GCP); ok {
		return x.GCP
	}
	return nil
}

func (x *ProvisionerDetails) GetAWS() *AWSProvisioner {
	if x, ok := x.GetData().(*ProvisionerDetails_AWS); ok {
		return x.AWS
	}
	return nil
}

func (x *ProvisionerDetails) GetAzure() *AzureProvisioner {
	if x, ok := x.GetData().(*ProvisionerDetails_Azure); ok {
		return x.Azure
	}
	return nil
}

func (x *ProvisionerDetails) GetACME() *ACMEProvisioner {
	if x, ok := x.GetData().(*ProvisionerDetails_ACME); ok {
		return x.ACME
	}
	return nil
}

func (x *ProvisionerDetails) GetX5C() *X5CProvisioner {
	if x, ok := x.GetData().(*ProvisionerDetails_X5C); ok {
		return x.X5C
	}
	return nil
}

func (x *ProvisionerDetails) GetK8SSA() *K8SSAProvisioner {
	if x, ok := x.GetData().(*ProvisionerDetails_K8SSA); ok {
		return x.K8SSA
	}
	return nil
}

func (x *ProvisionerDetails) GetSSHPOP() *SSHPOPProvisioner {
	if x, ok := x.GetData().(*ProvisionerDetails_SSHPOP); ok {
		return x.SSHPOP
	}
	return nil
}

func (x *ProvisionerDetails) GetSCEP() *SCEPProvisioner {
	if x, ok := x.GetData().(*ProvisionerDetails_SCEP); ok {
		return x.SCEP
	}
	return nil
}

type isProvisionerDetails_Data interface {
	isProvisionerDetails_Data()
}

type ProvisionerDetails_JWK struct {
	JWK *JWKProvisioner `protobuf:"bytes,20,opt,name=JWK,proto3,oneof"`
}

type ProvisionerDetails_OIDC struct {
	OIDC *OIDCProvisioner `protobuf:"bytes,21,opt,name=OIDC,proto3,oneof"`
}

type ProvisionerDetails_GCP struct {
	GCP *GCPProvisioner `protobuf:"bytes,22,opt,name=GCP,proto3,oneof"`
}

type ProvisionerDetails_AWS struct {
	AWS *AWSProvisioner `protobuf:"bytes,23,opt,name=AWS,proto3,oneof"`
}

type ProvisionerDetails_Azure struct {
	Azure *AzureProvisioner `protobuf:"bytes,24,opt,name=Azure,proto3,oneof"`
}

type ProvisionerDetails_ACME struct {
	ACME *ACMEProvisioner `protobuf:"bytes,25,opt,name=ACME,proto3,oneof"`
}

type ProvisionerDetails_X5C struct {
	X5C *X5CProvisioner `protobuf:"bytes,26,opt,name=X5C,proto3,oneof"`
}

type ProvisionerDetails_K8SSA struct {
	K8SSA *K8SSAProvisioner `protobuf:"bytes,27,opt,name=K8sSA,proto3,oneof"`
}

type ProvisionerDetails_SSHPOP struct {
	SSHPOP *SSHPOPProvisioner `protobuf:"bytes,28,opt,name=SSHPOP,proto3,oneof"`
}

type ProvisionerDetails_SCEP struct {
	SCEP *SCEPProvisioner `protobuf:"bytes,29,opt,name=SCEP,proto3,oneof"`
}

func (*ProvisionerDetails_JWK) isProvisionerDetails_Data() {}

func (*ProvisionerDetails_OIDC) isProvisionerDetails_Data() {}

func (*ProvisionerDetails_GCP) isProvisionerDetails_Data() {}

func (*ProvisionerDetails_AWS) isProvisionerDetails_Data() {}

func (*ProvisionerDetails_Azure) isProvisionerDetails_Data() {}

func (*ProvisionerDetails_ACME) isProvisionerDetails_Data() {}

func (*ProvisionerDetails_X5C) isProvisionerDetails_Data() {}

func (*ProvisionerDetails_K8SSA) isProvisionerDetails_Data() {}

func (*ProvisionerDetails_SSHPOP) isProvisionerDetails_Data() {}

func (*ProvisionerDetails_SCEP) isProvisionerDetails_Data() {}

type ProvisionerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Provisioners []*Provisioner `protobuf:"bytes,1,rep,name=provisioners,proto3" json:"provisioners,omitempty"`
}

func (x *ProvisionerList) Reset() {
	*x = ProvisionerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedca_provisioners_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvisionerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionerList) ProtoMessage() {}

func (x *ProvisionerList) ProtoReflect() protoreflect.Message {
	mi := &file_linkedca_provisioners_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionerList.ProtoReflect.Descriptor instead.
func (*ProvisionerList) Descriptor() ([]byte, []int) {
	return file_linkedca_provisioners_proto_rawDescGZIP(), []int{2}
}

func (x *ProvisionerList) GetProvisioners() []*Provisioner {
	if x != nil {
		return x.Provisioners
	}
	return nil
}

type Claims struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X509           *X509Claims `protobuf:"bytes,1,opt,name=x509,proto3" json:"x509,omitempty"`
	Ssh            *SSHClaims  `protobuf:"bytes,2,opt,name=ssh,proto3" json:"ssh,omitempty"`
	DisableRenewal bool        `protobuf:"varint,3,opt,name=disable_renewal,json=disableRenewal,proto3" json:"disable_renewal,omitempty"`
}

func (x *Claims) Reset() {
	*x = Claims{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedca_provisioners_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Claims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claims) ProtoMessage() {}

func (x *Claims) ProtoReflect() protoreflect.Message {
	mi := &file_linkedca_provisioners_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claims.ProtoReflect.Descriptor instead.
func (*Claims) Descriptor() ([]byte, []int) {
	return file_linkedca_provisioners_proto_rawDescGZIP(), []int{3}
}

func (x *Claims) GetX509() *X509Claims {
	if x != nil {
		return x.X509
	}
	return nil
}

func (x *Claims) GetSsh() *SSHClaims {
	if x != nil {
		return x.Ssh
	}
	return nil
}

func (x *Claims) GetDisableRenewal() bool {
	if x != nil {
		return x.DisableRenewal
	}
	return false
}

type X509Claims struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled   bool       `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Durations *Durations `protobuf:"bytes,2,opt,name=durations,proto3" json:"durations,omitempty"`
}

func (x *X509Claims) Reset() {
	*x = X509Claims{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedca_provisioners_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *X509Claims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X509Claims) ProtoMessage() {}

func (x *X509Claims) ProtoReflect() protoreflect.Message {
	mi := &file_linkedca_provisioners_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X509Claims.ProtoReflect.Descriptor instead.
func (*X509Claims) Descriptor() ([]byte, []int) {
	return file_linkedca_provisioners_proto_rawDescGZIP(), []int{4}
}

func (x *X509Claims) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *X509Claims) GetDurations() *Durations {
	if x != nil {
		return x.Durations
	}
	return nil
}

type SSHClaims struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled       bool       `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	UserDurations *Durations `protobuf:"bytes,2,opt,name=user_durations,json=userDurations,proto3" json:"user_durations,omitempty"`
	HostDurations *Durations `protobuf:"bytes,3,opt,name=host_durations,json=hostDurations,proto3" json:"host_durations,omitempty"`
}

func (x *SSHClaims) Reset() {
	*x = SSHClaims{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedca_provisioners_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSHClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHClaims) ProtoMessage() {}

func (x *SSHClaims) ProtoReflect() protoreflect.Message {
	mi := &file_linkedca_provisioners_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHClaims.ProtoReflect.Descriptor instead.
func (*SSHClaims) Descriptor() ([]byte, []int) {
	return file_linkedca_provisioners_proto_rawDescGZIP(), []int{5}
}

func (x *SSHClaims) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SSHClaims) GetUserDurations() *Durations {
	if x != nil {
		return x.UserDurations
	}
	return nil
}

func (x *SSHClaims) GetHostDurations() *Durations {
	if x != nil {
		return x.HostDurations
	}
	return nil
}

type Durations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Default string `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	Min     string `protobuf:"bytes,2,opt,name=min,proto3" json:"min,omitempty"`
	Max     string `protobuf:"bytes,3,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *Durations) Reset() {
	*x = Durations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedca_provisioners_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Durations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Durations) ProtoMessage() {}

func (x *Durations) ProtoReflect() protoreflect.Message {
	mi := &file_linkedca_provisioners_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Durations.ProtoReflect.Descriptor instead.
func (*Durations) Descriptor() ([]byte, []int) {
	return file_linkedca_provisioners_proto_rawDescGZIP(), []int{6}
}

func (x *Durations) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *Durations) GetMin() string {
	if x != nil {
		return x.Min
	}
	return ""
}

func (x *Durations) GetMax() string {
	if x != nil {
		return x.Max
	}
	return ""
}

type JWKProvisioner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey           []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	EncryptedPrivateKey []byte `protobuf:"bytes,2,opt,name=encrypted_private_key,json=encryptedPrivateKey,proto3" json:"encrypted_private_key,omitempty"`
}

func (x *JWKProvisioner) Reset() {
	*x = JWKProvisioner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedca_provisioners_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JWKProvisioner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWKProvisioner) ProtoMessage() {}

func (x *JWKProvisioner) ProtoReflect() protoreflect.Message {
	mi := &file_linkedca_provisioners_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWKProvisioner.ProtoReflect.Descriptor instead.
func (*JWKProvisioner) Descriptor() ([]byte, []int) {
	return file_linkedca_provisioners_proto_rawDescGZIP(), []int{7}
}

func (x *JWKProvisioner) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *JWKProvisioner) GetEncryptedPrivateKey() []byte {
	if x != nil {
		return x.EncryptedPrivateKey
	}
	return nil
}

type OIDCProvisioner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId              string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret          string   `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	ConfigurationEndpoint string   `protobuf:"bytes,3,opt,name=configuration_endpoint,json=configurationEndpoint,proto3" json:"configuration_endpoint,omitempty"`
	Admins                []string `protobuf:"bytes,4,rep,name=admins,proto3" json:"admins,omitempty"`
	Domains               []string `protobuf:"bytes,5,rep,name=domains,proto3" json:"domains,omitempty"`
	Groups                []string `protobuf:"bytes,6,rep,name=groups,proto3" json:"groups,omitempty"`
	ListenAddress         string   `protobuf:"bytes,7,opt,name=listen_address,json=listenAddress,proto3" json:"listen_address,omitempty"`
	TenantId              string   `protobuf:"bytes,8,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
}

func (x *OIDCProvisioner) Reset() {
	*x = OIDCProvisioner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedca_provisioners_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OIDCProvisioner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OIDCProvisioner) ProtoMessage() {}

func (x *OIDCProvisioner) ProtoReflect() protoreflect.Message {
	mi := &file_linkedca_provisioners_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OIDCProvisioner.ProtoReflect.Descriptor instead.
func (*OIDCProvisioner) Descriptor() ([]byte, []int) {
	return file_linkedca_provisioners_proto_rawDescGZIP(), []int{8}
}

func (x *OIDCProvisioner) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OIDCProvisioner) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *OIDCProvisioner) GetConfigurationEndpoint() string {
	if x != nil {
		return x.ConfigurationEndpoint
	}
	return ""
}

func (x *OIDCProvisioner) GetAdmins() []string {
	if x != nil {
		return x.Admins
	}
	return nil
}

func (x *OIDCProvisioner) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *OIDCProvisioner) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *OIDCProvisioner) GetListenAddress() string {
	if x != nil {
		return x.ListenAddress
	}
	return ""
}

func (x *OIDCProvisioner) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GCPProvisioner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceAccounts        []string `protobuf:"bytes,1,rep,name=service_accounts,json=serviceAccounts,proto3" json:"service_accounts,omitempty"`
	ProjectIds             []string `protobuf:"bytes,2,rep,name=project_ids,json=projectIds,proto3" json:"project_ids,omitempty"`
	DisableCustomSans      bool     `protobuf:"varint,3,opt,name=disable_custom_sans,json=disableCustomSans,proto3" json:"disable_custom_sans,omitempty"`
	DisableTrustOnFirstUse bool     `protobuf:"varint,4,opt,name=disable_trust_on_first_use,json=disableTrustOnFirstUse,proto3" json:"disable_trust_on_first_use,omitempty"`
	InstanceAge            string   `protobuf:"bytes,5,opt,name=instance_age,json=instanceAge,proto3" json:"instance_age,omitempty"`
}

func (x *GCPProvisioner) Reset() {
	*x = GCPProvisioner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedca_provisioners_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GCPProvisioner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCPProvisioner) ProtoMessage() {}

func (x *GCPProvisioner) ProtoReflect() protoreflect.Message {
	mi := &file_linkedca_provisioners_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCPProvisioner.ProtoReflect.Descriptor instead.
func (*GCPProvisioner) Descriptor() ([]byte, []int) {
	return file_linkedca_provisioners_proto_rawDescGZIP(), []int{9}
}

func (x *GCPProvisioner) GetServiceAccounts() []string {
	if x != nil {
		return x.ServiceAccounts
	}
	return nil
}

func (x *GCPProvisioner) GetProjectIds() []string {
	if x != nil {
		return x.ProjectIds
	}
	return nil
}

func (x *GCPProvisioner) GetDisableCustomSans() bool {
	if x != nil {
		return x.DisableCustomSans
	}
	return false
}

func (x *GCPProvisioner) GetDisableTrustOnFirstUse() bool {
	if x != nil {
		return x.DisableTrustOnFirstUse
	}
	return false
}

func (x *GCPProvisioner) GetInstanceAge() string {
	if x != nil {
		return x.InstanceAge
	}
	return ""
}

type AWSProvisioner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accounts               []string `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	DisableCustomSans      bool     `protobuf:"varint,2,opt,name=disable_custom_sans,json=disableCustomSans,proto3" json:"disable_custom_sans,omitempty"`
	DisableTrustOnFirstUse bool     `protobuf:"varint,3,opt,name=disable_trust_on_first_use,json=disableTrustOnFirstUse,proto3" json:"disable_trust_on_first_use,omitempty"`
	InstanceAge            string   `protobuf:"bytes,4,opt,name=instance_age,json=instanceAge,proto3" json:"instance_age,omitempty"`
}

func (x *AWSProvisioner) Reset() {
	*x = AWSProvisioner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedca_provisioners_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AWSProvisioner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AWSProvisioner) ProtoMessage() {}

func (x *AWSProvisioner) ProtoReflect() protoreflect.Message {
	mi := &file_linkedca_provisioners_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AWSProvisioner.ProtoReflect.Descriptor instead.
func (*AWSProvisioner) Descriptor() ([]byte, []int) {
	return file_linkedca_provisioners_proto_rawDescGZIP(), []int{10}
}

func (x *AWSProvisioner) GetAccounts() []string {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *AWSProvisioner) GetDisableCustomSans() bool {
	if x != nil {
		return x.DisableCustomSans
	}
	return false
}

func (x *AWSProvisioner) GetDisableTrustOnFirstUse() bool {
	if x != nil {
		return x.DisableTrustOnFirstUse
	}
	return false
}

func (x *AWSProvisioner) GetInstanceAge() string {
	if x != nil {
		return x.InstanceAge
	}
	return ""
}

type AzureProvisioner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId               string   `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ResourceGroups         []string `protobuf:"bytes,2,rep,name=resource_groups,json=resourceGroups,proto3" json:"resource_groups,omitempty"`
	Audience               string   `protobuf:"bytes,3,opt,name=audience,proto3" json:"audience,omitempty"`
	DisableCustomSans      bool     `protobuf:"varint,4,opt,name=disable_custom_sans,json=disableCustomSans,proto3" json:"disable_custom_sans,omitempty"`
	DisableTrustOnFirstUse bool     `protobuf:"varint,5,opt,name=disable_trust_on_first_use,json=disableTrustOnFirstUse,proto3" json:"disable_trust_on_first_use,omitempty"`
}

func (x *AzureProvisioner) Reset() {
	*x = AzureProvisioner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedca_provisioners_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AzureProvisioner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureProvisioner) ProtoMessage() {}

func (x *AzureProvisioner) ProtoReflect() protoreflect.Message {
	mi := &file_linkedca_provisioners_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureProvisioner.ProtoReflect.Descriptor instead.
func (*AzureProvisioner) Descriptor() ([]byte, []int) {
	return file_linkedca_provisioners_proto_rawDescGZIP(), []int{11}
}

func (x *AzureProvisioner) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AzureProvisioner) GetResourceGroups() []string {
	if x != nil {
		return x.ResourceGroups
	}
	return nil
}

func (x *AzureProvisioner) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *AzureProvisioner) GetDisableCustomSans() bool {
	if x != nil {
		return x.DisableCustomSans
	}
	return false
}

func (x *AzureProvisioner) GetDisableTrustOnFirstUse() bool {
	if x != nil {
		return x.DisableTrustOnFirstUse
	}
	return false
}

type ACMEProvisioner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ForceCn bool `protobuf:"varint,1,opt,name=force_cn,json=forceCn,proto3" json:"force_cn,omitempty"`
}

func (x *ACMEProvisioner) Reset() {
	*x = ACMEProvisioner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedca_provisioners_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ACMEProvisioner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACMEProvisioner) ProtoMessage() {}

func (x *ACMEProvisioner) ProtoReflect() protoreflect.Message {
	mi := &file_linkedca_provisioners_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACMEProvisioner.ProtoReflect.Descriptor instead.
func (*ACMEProvisioner) Descriptor() ([]byte, []int) {
	return file_linkedca_provisioners_proto_rawDescGZIP(), []int{12}
}

func (x *ACMEProvisioner) GetForceCn() bool {
	if x != nil {
		return x.ForceCn
	}
	return false
}

type X5CProvisioner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roots [][]byte `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
}

func (x *X5CProvisioner) Reset() {
	*x = X5CProvisioner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedca_provisioners_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *X5CProvisioner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X5CProvisioner) ProtoMessage() {}

func (x *X5CProvisioner) ProtoReflect() protoreflect.Message {
	mi := &file_linkedca_provisioners_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X5CProvisioner.ProtoReflect.Descriptor instead.
func (*X5CProvisioner) Descriptor() ([]byte, []int) {
	return file_linkedca_provisioners_proto_rawDescGZIP(), []int{13}
}

func (x *X5CProvisioner) GetRoots() [][]byte {
	if x != nil {
		return x.Roots
	}
	return nil
}

type K8SSAProvisioner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKeys [][]byte `protobuf:"bytes,1,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
}

func (x *K8SSAProvisioner) Reset() {
	*x = K8SSAProvisioner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedca_provisioners_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *K8SSAProvisioner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SSAProvisioner) ProtoMessage() {}

func (x *K8SSAProvisioner) ProtoReflect() protoreflect.Message {
	mi := &file_linkedca_provisioners_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SSAProvisioner.ProtoReflect.Descriptor instead.
func (*K8SSAProvisioner) Descriptor() ([]byte, []int) {
	return file_linkedca_provisioners_proto_rawDescGZIP(), []int{14}
}

func (x *K8SSAProvisioner) GetPublicKeys() [][]byte {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

type SSHPOPProvisioner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SSHPOPProvisioner) Reset() {
	*x = SSHPOPProvisioner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedca_provisioners_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSHPOPProvisioner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHPOPProvisioner) ProtoMessage() {}

func (x *SSHPOPProvisioner) ProtoReflect() protoreflect.Message {
	mi := &file_linkedca_provisioners_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHPOPProvisioner.ProtoReflect.Descriptor instead.
func (*SSHPOPProvisioner) Descriptor() ([]byte, []int) {
	return file_linkedca_provisioners_proto_rawDescGZIP(), []int{15}
}

type SCEPProvisioner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ForceCn                bool     `protobuf:"varint,1,opt,name=force_cn,json=forceCn,proto3" json:"force_cn,omitempty"`
	Challenge              string   `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Capabilities           []string `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	MinimumPublicKeyLength int32    `protobuf:"varint,4,opt,name=minimum_public_key_length,json=minimumPublicKeyLength,proto3" json:"minimum_public_key_length,omitempty"`
}

func (x *SCEPProvisioner) Reset() {
	*x = SCEPProvisioner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedca_provisioners_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCEPProvisioner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCEPProvisioner) ProtoMessage() {}

func (x *SCEPProvisioner) ProtoReflect() protoreflect.Message {
	mi := &file_linkedca_provisioners_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCEPProvisioner.ProtoReflect.Descriptor instead.
func (*SCEPProvisioner) Descriptor() ([]byte, []int) {
	return file_linkedca_provisioners_proto_rawDescGZIP(), []int{16}
}

func (x *SCEPProvisioner) GetForceCn() bool {
	if x != nil {
		return x.ForceCn
	}
	return false
}

func (x *SCEPProvisioner) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *SCEPProvisioner) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *SCEPProvisioner) GetMinimumPublicKeyLength() int32 {
	if x != nil {
		return x.MinimumPublicKeyLength
	}
	return 0
}

var File_linkedca_provisioners_proto protoreflect.FileDescriptor

var file_linkedca_provisioners_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x63, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6c,
	0x69, 0x6e, 0x6b, 0x65, 0x64, 0x63, 0x61, 0x22, 0xfe, 0x03, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65,
	0x64, 0x63, 0x61, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x36,
	0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x63, 0x61, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x07, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x63,
	0x61, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x52, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73,
	0x12, 0x23, 0x0a, 0x0d, 0x78, 0x35, 0x30, 0x39, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x78, 0x35, 0x30, 0x39, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x78, 0x35, 0x30, 0x39, 0x5f, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x10, 0x78, 0x35, 0x30, 0x39, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x73, 0x68, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x73, 0x73, 0x68, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x73, 0x73, 0x68, 0x5f, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0f, 0x73, 0x73, 0x68, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x74, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f,
	0x4f, 0x50, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4a, 0x57, 0x4b, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x4f, 0x49, 0x44, 0x43, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x43, 0x50, 0x10, 0x03,
	0x12, 0x07, 0x0a, 0x03, 0x41, 0x57, 0x53, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x5a, 0x55,
	0x52, 0x45, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x41, 0x43, 0x4d, 0x45, 0x10, 0x06, 0x12, 0x07,
	0x0a, 0x03, 0x58, 0x35, 0x43, 0x10, 0x07, 0x12, 0x09, 0x0a, 0x05, 0x4b, 0x38, 0x53, 0x53, 0x41,
	0x10, 0x08, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x53, 0x48, 0x50, 0x4f, 0x50, 0x10, 0x09, 0x12, 0x08,
	0x0a, 0x04, 0x53, 0x43, 0x45, 0x50, 0x10, 0x0a, 0x22, 0x86, 0x04, 0x0a, 0x12, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12,
	0x2c, 0x0a, 0x03, 0x4a, 0x57, 0x4b, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c,
	0x69, 0x6e, 0x6b, 0x65, 0x64, 0x63, 0x61, 0x2e, 0x4a, 0x57, 0x4b, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x48, 0x00, 0x52, 0x03, 0x4a, 0x57, 0x4b, 0x12, 0x2f, 0x0a,
	0x04, 0x4f, 0x49, 0x44, 0x43, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x69,
	0x6e, 0x6b, 0x65, 0x64, 0x63, 0x61, 0x2e, 0x4f, 0x49, 0x44, 0x43, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x48, 0x00, 0x52, 0x04, 0x4f, 0x49, 0x44, 0x43, 0x12, 0x2c,
	0x0a, 0x03, 0x47, 0x43, 0x50, 0x18, 0x16, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69,
	0x6e, 0x6b, 0x65, 0x64, 0x63, 0x61, 0x2e, 0x47, 0x43, 0x50, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x65, 0x72, 0x48, 0x00, 0x52, 0x03, 0x47, 0x43, 0x50, 0x12, 0x2c, 0x0a, 0x03,
	0x41, 0x57, 0x53, 0x18, 0x17, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69, 0x6e, 0x6b,
	0x65, 0x64, 0x63, 0x61, 0x2e, 0x41, 0x57, 0x53, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x65, 0x72, 0x48, 0x00, 0x52, 0x03, 0x41, 0x57, 0x53, 0x12, 0x32, 0x0a, 0x05, 0x41, 0x7a,
	0x75, 0x72, 0x65, 0x18, 0x18, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x69, 0x6e, 0x6b,
	0x65, 0x64, 0x63, 0x61, 0x2e, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x65, 0x72, 0x48, 0x00, 0x52, 0x05, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x12, 0x2f,
	0x0a, 0x04, 0x41, 0x43, 0x4d, 0x45, 0x18, 0x19, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c,
	0x69, 0x6e, 0x6b, 0x65, 0x64, 0x63, 0x61, 0x2e, 0x41, 0x43, 0x4d, 0x45, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x48, 0x00, 0x52, 0x04, 0x41, 0x43, 0x4d, 0x45, 0x12,
	0x2c, 0x0a, 0x03, 0x58, 0x35, 0x43, 0x18, 0x1a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c,
	0x69, 0x6e, 0x6b, 0x65, 0x64, 0x63, 0x61, 0x2e, 0x58, 0x35, 0x43, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x48, 0x00, 0x52, 0x03, 0x58, 0x35, 0x43, 0x12, 0x32, 0x0a,
	0x05, 0x4b, 0x38, 0x73, 0x53, 0x41, 0x18, 0x1b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c,
	0x69, 0x6e, 0x6b, 0x65, 0x64, 0x63, 0x61, 0x2e, 0x4b, 0x38, 0x73, 0x53, 0x41, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x48, 0x00, 0x52, 0x05, 0x4b, 0x38, 0x73, 0x53,
	0x41, 0x12, 0x35, 0x0a, 0x06, 0x53, 0x53, 0x48, 0x50, 0x4f, 0x50, 0x18, 0x1c, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x63, 0x61, 0x2e, 0x53, 0x53, 0x48,
	0x50, 0x4f, 0x50, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x48, 0x00,
	0x52, 0x06, 0x53, 0x53, 0x48, 0x50, 0x4f, 0x50, 0x12, 0x2f, 0x0a, 0x04, 0x53, 0x43, 0x45, 0x50,
	0x18, 0x1d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x63,
	0x61, 0x2e, 0x53, 0x43, 0x45, 0x50, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65,
	0x72, 0x48, 0x00, 0x52, 0x04, 0x53, 0x43, 0x45, 0x50, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x4c, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x69, 0x6e,
	0x6b, 0x65, 0x64, 0x63, 0x61, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65,
	0x72, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x73, 0x22,
	0x82, 0x01, 0x0a, 0x06, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12, 0x28, 0x0a, 0x04, 0x78, 0x35,
	0x30, 0x39, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65,
	0x64, 0x63, 0x61, 0x2e, 0x58, 0x35, 0x30, 0x39, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x52, 0x04,
	0x78, 0x35, 0x30, 0x39, 0x12, 0x25, 0x0a, 0x03, 0x73, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x63, 0x61, 0x2e, 0x53, 0x53, 0x48,
	0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x52, 0x03, 0x73, 0x73, 0x68, 0x12, 0x27, 0x0a, 0x0f, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x6e, 0x65, 0x77, 0x61, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x6e,
	0x65, 0x77, 0x61, 0x6c, 0x22, 0x59, 0x0a, 0x0a, 0x58, 0x35, 0x30, 0x39, 0x43, 0x6c, 0x61, 0x69,
	0x6d, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x31, 0x0a, 0x09,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x63, 0x61, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x09, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x9d, 0x01, 0x0a, 0x09, 0x53, 0x53, 0x48, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x3a, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x63, 0x61, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x3a, 0x0a, 0x0e, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x69,
	0x6e, 0x6b, 0x65, 0x64, 0x63, 0x61, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x0d, 0x68, 0x6f, 0x73, 0x74, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x49, 0x0a, 0x09, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x63, 0x0a, 0x0e, 0x4a, 0x57,
	0x4b, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x32, 0x0a, 0x15, 0x65,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x13, 0x65, 0x6e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x65, 0x64, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x22,
	0x98, 0x02, 0x0a, 0x0f, 0x4f, 0x49, 0x44, 0x43, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x35, 0x0a, 0x16, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x22, 0xeb, 0x01, 0x0a, 0x0e, 0x47,
	0x43, 0x50, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x12, 0x29, 0x0a,
	0x10, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x64, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x73, 0x61, 0x6e, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x53, 0x61, 0x6e, 0x73, 0x12, 0x3a, 0x0a, 0x1a, 0x64, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x5f, 0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x6f, 0x6e, 0x5f, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x16, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x4f, 0x6e, 0x46, 0x69, 0x72,
	0x73, 0x74, 0x55, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x5f, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x67, 0x65, 0x22, 0xbb, 0x01, 0x0a, 0x0e, 0x41, 0x57, 0x53,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x64, 0x69, 0x73, 0x61, 0x62,
	0x6c, 0x65, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x73, 0x61, 0x6e, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x53, 0x61, 0x6e, 0x73, 0x12, 0x3a, 0x0a, 0x1a, 0x64, 0x69, 0x73, 0x61, 0x62,
	0x6c, 0x65, 0x5f, 0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x6f, 0x6e, 0x5f, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x5f, 0x75, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x16, 0x64, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x4f, 0x6e, 0x46, 0x69, 0x72, 0x73, 0x74,
	0x55, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x41, 0x67, 0x65, 0x22, 0xe0, 0x01, 0x0a, 0x10, 0x41, 0x7a, 0x75, 0x72, 0x65,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x74,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x2e, 0x0a,
	0x13, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f,
	0x73, 0x61, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x64, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x53, 0x61, 0x6e, 0x73, 0x12, 0x3a, 0x0a,
	0x1a, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x6f,
	0x6e, 0x5f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x16, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x4f,
	0x6e, 0x46, 0x69, 0x72, 0x73, 0x74, 0x55, 0x73, 0x65, 0x22, 0x2c, 0x0a, 0x0f, 0x41, 0x43, 0x4d,
	0x45, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08,
	0x66, 0x6f, 0x72, 0x63, 0x65, 0x5f, 0x63, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x66, 0x6f, 0x72, 0x63, 0x65, 0x43, 0x6e, 0x22, 0x26, 0x0a, 0x0e, 0x58, 0x35, 0x43, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6f,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x74, 0x73, 0x22,
	0x33, 0x0a, 0x10, 0x4b, 0x38, 0x73, 0x53, 0x41, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65,
	0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x53, 0x48, 0x50, 0x4f, 0x50, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x22, 0xa9, 0x01, 0x0a, 0x0f, 0x53, 0x43,
	0x45, 0x50, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x12, 0x19, 0x0a,
	0x08, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x5f, 0x63, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x43, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6c,
	0x6c, 0x65, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61,
	0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61,
	0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x19, 0x6d, 0x69,
	0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79,
	0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x16, 0x6d,
	0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x4c,
	0x65, 0x6e, 0x67, 0x74, 0x68, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x73, 0x74, 0x65, 0x70, 0x2f, 0x63, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x65,
	0x64, 0x63, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_linkedca_provisioners_proto_rawDescOnce sync.Once
	file_linkedca_provisioners_proto_rawDescData = file_linkedca_provisioners_proto_rawDesc
)

func file_linkedca_provisioners_proto_rawDescGZIP() []byte {
	file_linkedca_provisioners_proto_rawDescOnce.Do(func() {
		file_linkedca_provisioners_proto_rawDescData = protoimpl.X.CompressGZIP(file_linkedca_provisioners_proto_rawDescData)
	})
	return file_linkedca_provisioners_proto_rawDescData
}

var file_linkedca_provisioners_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_linkedca_provisioners_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_linkedca_provisioners_proto_goTypes = []interface{}{
	(Provisioner_Type)(0),      // 0: linkedca.Provisioner.Type
	(*Provisioner)(nil),        // 1: linkedca.Provisioner
	(*ProvisionerDetails)(nil), // 2: linkedca.ProvisionerDetails
	(*ProvisionerList)(nil),    // 3: linkedca.ProvisionerList
	(*Claims)(nil),             // 4: linkedca.Claims
	(*X509Claims)(nil),         // 5: linkedca.X509Claims
	(*SSHClaims)(nil),          // 6: linkedca.SSHClaims
	(*Durations)(nil),          // 7: linkedca.Durations
	(*JWKProvisioner)(nil),     // 8: linkedca.JWKProvisioner
	(*OIDCProvisioner)(nil),    // 9: linkedca.OIDCProvisioner
	(*GCPProvisioner)(nil),     // 10: linkedca.GCPProvisioner
	(*AWSProvisioner)(nil),     // 11: linkedca.AWSProvisioner
	(*AzureProvisioner)(nil),   // 12: linkedca.AzureProvisioner
	(*ACMEProvisioner)(nil),    // 13: linkedca.ACMEProvisioner
	(*X5CProvisioner)(nil),     // 14: linkedca.X5CProvisioner
	(*K8SSAProvisioner)(nil),   // 15: linkedca.K8sSAProvisioner
	(*SSHPOPProvisioner)(nil),  // 16: linkedca.SSHPOPProvisioner
	(*SCEPProvisioner)(nil),    // 17: linkedca.SCEPProvisioner
}
var file_linkedca_provisioners_proto_depIdxs = []int32{
	0,  // 0: linkedca.Provisioner.type:type_name -> linkedca.Provisioner.Type
	2,  // 1: linkedca.Provisioner.details:type_name -> linkedca.ProvisionerDetails
	4,  // 2: linkedca.Provisioner.claims:type_name -> linkedca.Claims
	8,  // 3: linkedca.ProvisionerDetails.JWK:type_name -> linkedca.JWKProvisioner
	9,  // 4: linkedca.ProvisionerDetails.OIDC:type_name -> linkedca.OIDCProvisioner
	10, // 5: linkedca.ProvisionerDetails.GCP:type_name -> linkedca.GCPProvisioner
	11, // 6: linkedca.ProvisionerDetails.AWS:type_name -> linkedca.AWSProvisioner
	12, // 7: linkedca.ProvisionerDetails.Azure:type_name -> linkedca.AzureProvisioner
	13, // 8: linkedca.ProvisionerDetails.ACME:type_name -> linkedca.ACMEProvisioner
	14, // 9: linkedca.ProvisionerDetails.X5C:type_name -> linkedca.X5CProvisioner
	15, // 10: linkedca.ProvisionerDetails.K8sSA:type_name -> linkedca.K8sSAProvisioner
	16, // 11: linkedca.ProvisionerDetails.SSHPOP:type_name -> linkedca.SSHPOPProvisioner
	17, // 12: linkedca.ProvisionerDetails.SCEP:type_name -> linkedca.SCEPProvisioner
	1,  // 13: linkedca.ProvisionerList.provisioners:type_name -> linkedca.Provisioner
	5,  // 14: linkedca.Claims.x509:type_name -> linkedca.X509Claims
	6,  // 15: linkedca.Claims.ssh:type_name -> linkedca.SSHClaims
	7,  // 16: linkedca.X509Claims.durations:type_name -> linkedca.Durations
	7,  // 17: linkedca.SSHClaims.user_durations:type_name -> linkedca.Durations
	7,  // 18: linkedca.SSHClaims.host_durations:type_name -> linkedca.Durations
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_linkedca_provisioners_proto_init() }
func file_linkedca_provisioners_proto_init() {
	if File_linkedca_provisioners_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_linkedca_provisioners_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Provisioner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedca_provisioners_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProvisionerDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedca_provisioners_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProvisionerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedca_provisioners_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Claims); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedca_provisioners_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*X509Claims); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedca_provisioners_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSHClaims); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedca_provisioners_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Durations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedca_provisioners_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JWKProvisioner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedca_provisioners_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OIDCProvisioner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedca_provisioners_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GCPProvisioner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedca_provisioners_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AWSProvisioner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedca_provisioners_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AzureProvisioner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedca_provisioners_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ACMEProvisioner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedca_provisioners_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*X5CProvisioner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedca_provisioners_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*K8SSAProvisioner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedca_provisioners_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSHPOPProvisioner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedca_provisioners_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCEPProvisioner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_linkedca_provisioners_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ProvisionerDetails_JWK)(nil),
		(*ProvisionerDetails_OIDC)(nil),
		(*ProvisionerDetails_GCP)(nil),
		(*ProvisionerDetails_AWS)(nil),
		(*ProvisionerDetails_Azure)(nil),
		(*ProvisionerDetails_ACME)(nil),
		(*ProvisionerDetails_X5C)(nil),
		(*ProvisionerDetails_K8SSA)(nil),
		(*ProvisionerDetails_SSHPOP)(nil),
		(*ProvisionerDetails_SCEP)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_linkedca_provisioners_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_linkedca_provisioners_proto_goTypes,
		DependencyIndexes: file_linkedca_provisioners_proto_depIdxs,
		EnumInfos:         file_linkedca_provisioners_proto_enumTypes,
		MessageInfos:      file_linkedca_provisioners_proto_msgTypes,
	}.Build()
	File_linkedca_provisioners_proto = out.File
	file_linkedca_provisioners_proto_rawDesc = nil
	file_linkedca_provisioners_proto_goTypes = nil
	file_linkedca_provisioners_proto_depIdxs = nil
}
