apiVersion: v1
kind: Namespace
metadata:
  name: step-ca
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: step-ca
  namespace: step-ca
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: step-ca-tokenreviewer
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: step-ca-tokenreviewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: step-ca-tokenreviewer
subjects:
  - kind: ServiceAccount
    name: step-ca
    namespace: step-ca
