name: Frizbee pinning check
on:
  push:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  frizbee:
    uses: smallstep/workflows/.github/workflows/frizbee.yml@main
    secrets: inherit
